# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_manipulator_controller:
  ros__parameters:
    joints:
      - joint_left
      - l_joint_1
      - l_joint_2
      - l_joint_3
      - l_joint_4
      - l_joint_5
      - l_joint_6
      - l_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_manipulator_controller:
  ros__parameters:
    joints:
      - joint_right
      - r_joint_1
      - r_joint_2
      - r_joint_3
      - r_joint_4
      - r_joint_5
      - r_joint_6
      - r_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity