controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - r_joint_1
      - r_joint_2
      - r_joint_3
      - r_joint_4
      - r_joint_5
      - r_joint_6
      # - r_joint_7
      # - r_tool_joint
      # - r_end_joint1
      # - r_end_joint2
      # - r_end_joint3
      # - r_end_joint4
      # - r_end_joint5
      - l_joint_1
      - l_joint_2
      - l_joint_3
      - l_joint_4
      - l_joint_5
      - l_joint_6
      # - l_joint_7
      - joint_right
      - joint_left
      - mobile_left_wheel_joint
      - mobile_right_wheel_joint
      - mobile_fl_caster_rotation_joint
      - mobile_fl_caster_wheel_joint
      - mobile_fr_caster_rotation_joint
      - mobile_fr_caster_wheel_joint
      - mobile_bl_caster_rotation_joint
      - mobile_bl_caster_wheel_joint
      - mobile_br_caster_rotation_joint
      - mobile_br_caster_wheel_joint


joint_trajectory_controller:
  ros__parameters:
    joints:
      - r_joint_1
      - r_joint_2
      - r_joint_3
      - r_joint_4
      - r_joint_5
      - r_joint_6
      # - r_joint_7
      # - r_tool_joint
      # - r_end_joint1
      # - r_end_joint2
      # - r_end_joint3
      # - r_end_joint4
      # - r_end_joint5
      - l_joint_1
      - l_joint_2
      - l_joint_3
      - l_joint_4
      - l_joint_5
      - l_joint_6
      # - l_joint_7
      - joint_right
      - joint_left
      - mobile_left_wheel_joint
      - mobile_right_wheel_joint
      - mobile_fl_caster_rotation_joint
      - mobile_fl_caster_wheel_joint
      - mobile_fr_caster_rotation_joint
      - mobile_fr_caster_wheel_joint
      - mobile_bl_caster_rotation_joint
      - mobile_bl_caster_wheel_joint
      - mobile_br_caster_rotation_joint
      - mobile_br_caster_wheel_joint
    command_interfaces:
      - position

    state_interfaces:
      - position
